### PR TITLE
first draft of vertex types w/definitions

### PR DESCRIPTION
**Pull request by crherlihy**
Hi all. This PR relates to #21 and includes a first draft of vertex type definitions that we can use to write edge constraints, and implement extraction functions to build a non-trivial (but still relatively rudimentary) knowledge graph for our flu meta-model example.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
We also need both `program_formula` and `mathematical_formula` types.

**Comment by crherlihy** [comment]
@jpfairbanks to address your comments:

- agree re: machine vs. program interpretable. Was debating on name choice there. There's probably a case for another high level category that is lower level (eg x86); do you think we should also consider a high level category for intermediate level Julia instructions, per how we are planning to use cassette?

- By `function_level_parameter` I specifically meant the parameters that are part of the function definition, as distinguished from the args with which a function is called, and/or variables that appear within a function (generally local variables). Do you think this distinction makes sense/is necessary? 

- Re: `program_value` and `program_variable`, do you specifically mean static numeric values? I think it makes sense to have specific cases where a variable is assigned to 'hold/represent' a numeric value (I included a `numeric_value` vertex type for this reason). For the sake of clarity I'd like to distinguish that from cases where a variable is a placeholder for an object/data structure. With respect to SSA stuff, this makes sense but requires access to intermediate representation of the code; not sure if your intention here also extends to covering functional programming use cases where mutable variables are discouraged?

- will review multiple dispatch and update accordingly.

- re: aggregation; that's an interesting point. was thinking about it more in the economics sense of the term. What I'm after here is a way to express that a population is composed of units (n>1; units \in {people, animals, etc.}). It will help us parse the SIR models since compartments are associated with/intended to represent (sub)populations, and we want to ensure that type of aggregate group/entity is unitful in a programmatic sense. Am in favor of changing name to `collection`.

**Comment by jpfairbanks** [comment]
> agree re: machine vs. program interpretable. Was debating on name choice there. There's probably a case for another high level category that is lower level (eg x86); do you think we should also consider a high level category for intermediate level Julia instructions, per how we are planning to use cassette?

Yeah I think we want `Expr`, `CodeInfo`, and `SSAValue` vertex types, because those map directly onto the representation in the Julia internals. 

> By function_level_parameter I specifically meant the parameters that are part of the function definition, as distinguished from the args with which a function is called, and/or variables that appear within a function (generally local variables). Do you think this distinction makes sense/is necessary?

Yeah I think distinguishing between arguments, parameters, and assignments make sense, also the distinction between values and the variables that hold those values. Maybe we want to use some definitions like:

||value|variables|
|--|--|--|
|input|argument|parameter|
|assignment|assigned value|variable|

I don't have strong opinions about what the names are but we should differentiate those concepts.

> Re: program_value and program_variable, do you specifically mean static numeric values? I think it makes sense to have specific cases where a variable is assigned to 'hold/represent' a numeric value (I included a numeric_value vertex type for this reason). For the sake of clarity I'd like to distinguish that from cases where a variable is a placeholder for an object/data structure. With respect to SSA stuff, this makes sense but requires access to intermediate representation of the code; not sure if your intention here also extends to covering functional programming use cases where mutable variables are discouraged?
> 
> will review multiple dispatch and update accordingly.
> 
> re: aggregation; that's an interesting point. was thinking about it more in the economics sense of the term. What I'm after here is a way to express that a population is composed of units (n>1; units \in {people, animals, etc.}).

Does unit in that sentence mean unit like "meters, second, ..." or something like "individuals in a population"? 

> It will help us parse the SIR models since compartments are associated with/intended to represent (sub)populations, and we want to ensure that type of aggregate group/entity is unitful in a programmatic sense. Am in favor of changing name to collection.

Yeah that makes sense `collection` is much more natural from a PL perspective.

**Comment by jpfairbanks** [comment]
Based on our discussion today, I think we should:

- [ ] use `function -> method -> argumenttuple -> argument` to represent multiple dispatch.
- [ ] represent OOP as the subset of MD that is truly is (ie. 1problem.solve(algorithm)` ==> `solve(problem, algorithm)`
- [ ] call the LHS of all assignment operations *Variable* and use *Argument* for the inputs to a method and *Return Value* for the output of a method
- [ ] Punt on explicitly representing scopes for now, so that variable is defined in a function or represented as a global.
- [ ] distinguish math functions from code functions. Math functions would bet taken from a list like https://github.com/JuliaLang/julia/blob/master/base/math.jl or https://docs.julialang.org/en/v1/base/math/index.html#Mathematical-Functions-1

An illustrative example for the documentation is:

```julia
function f(x=0.4, y=3)
    z = x*y
    return z
end
```

```julia
f -> f(x::Float, y::Float) -> (Float,Float) -> Float 
x-> "x", x-> Float
y -> "y", y-> Float
f(x::Float, y::Float) -> x
f(x::Float, y::Float) -> y
x -> 0.4
y -> 3
z -> Float
* -> (Float,Float) -> Float
f(x::Float, y::Float) -> z 
```

The decision of what information should be vertex metadata and what should be edges is hard, so lets make everything edges in the schema but then reserve the right to implement some of those edge types as metadata for performance or visualization purposes.

**Comment by crherlihy** [comment]
@jpfairbanks have made the edits we discussed today. representation of OOP will be resolved via parsing. One thing I added to keep return values consistent with arg and arg tuples is one vertex type for `return_value` and another for `return_tuple`, since Julia lets you simulate returning multiple values with a tuple.

**Pull request merged**
