### PR TITLE
Compare programs

### PR DESCRIPTION
**Pull request by crherlihy**
This is a WIP to use code_lowered to build a high-level call graph and func->variable association graph (to address #118). Since our focus is on which variables functions reference, numeric values are not currently supported (e.g., only args that are passed in and mapped to slot names are captured). We can modify this in the future, but that will require us to think about whether we want initial values only or dynamic values over time. 

The notebook includes some toy functions, and then shows how the graph-building function works for some of them and fails for others. Have been trying to debug and suspect it's related to low-level behavior of the code_lowered macro, but haven't figured out how to solve yet. The docs on this suggest that it may be related to the way that macro handles generated vs. non-generated functions. 

Not ready to merge yet but wanted to open PR so we can discuss best path forward.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
1. I like the use of a user defined struct MethodCallsSubroutineFrame
2. I think you create this data frame (`df = DataFrame(src = Function[], dst = Any[], dst_args = Any[], edge_type=String[])`) before a bunch of function definitions, which I thought was going to be used as a closure variable in those functions, but I don't see any references to `df` in those functions, did this closure variable get replaced by the argument `input_df`?
3. I think you might want to go with something other than a string here: `frame = MethodCallsSubroutineFrame(f, callee, (), "method_calls_subroutine")`. 
   - If there is a short list of these possible values (where short is like <64K) a symbol will be more efficient.
   - If they are going to be used to switch on, we might consider an empty struct there (this has serialization concerns)
4.  for the `MethodInteractWithVarFrame` (maybe we shorten that to `InteractionFrame`?) I see some places for improvement:
     - `df = DataFrame(src = Function[], dst = Symbol[], dst_args = Expr[], edge_type=String[])` and then `function get_set_V(f, args...)`. I think it is better to split this into 3 functions 
        1) `interactions(f, args...)::Vector{InteractionFrame}` and 
        2) DataFrame(v::Vector{InteractionFrame})
        3) append!(df::DataFrame, v::Vector{InteractionFrame}). 
  
        That way we can decouple the extraction of the edges with the storage in a DataFrame object. 
    - `Expr(:nothing)` I'm not sure what this is trying to represent, but some other options for representing missing values are:
        1) `nothing`: this is the nuclear option of missing values, basically a null pointer.
        2) `:nothing`: the symbol of nothing
        3) `Nothing`: the singleton datatype that represents the concept of nothingness
        4) `()`: the empty tuple
        5) `:()` the empty expression, an expression that when evaluated instantiates an empty tuple
        6) Any expression with just a `:head` and no args ie 
        ```julia 
        julia> dump(Expr(:a))
        Expr
          head: Symbol a
          args: Array{Any}((0,))
        ```
        7) `missing, :missing, Missing` same as (a,b,c) but for statistical missing like N/A or SQL's NULL.
        I would pick the value from this list that matches the type of what you have in mind when the data won't be missing/null/empty tuple.

**Comment by jpfairbanks** [comment]
@crherlihy I took a look at `@code_typed` and you can get the type information out of the Core.PiNode objects int he CodeInfo Object

```julia

julia> @code_typed f(1,2)
CodeInfo(
2 1 ─ %1 = (Base.mul_int)(a, b)::Int64                                                                                                                                 │╻ *
  │   %2 = (Base.add_int)(%1, b)::Int64                                                                                                                                │╻ +
  └──      return %2                                                                                                                                                   │
) => Int64

julia> @code_typed f(1,2.0)
CodeInfo(
2 1 ─ %1 = (Base.sitofp)(Float64, a)::Float64                                                                                                                     │╻╷╷╷╷ *
  │   %2 = (Base.mul_float)(%1, b)::Float64                                                                                                                       ││╻     *
  │   %3 = (Base.add_float)(%2, b)::Float64                                                                                                                       │╻     +
  └──      return %3                                                                                                                                              │
) => Float64

julia> @code_lowered f(1,2.0)
CodeInfo(
2 1 ─ %1 = a * b                                                                                                                                                          │
  │   %2 = %1 + b                                                                                                                                                         │
  └──      return %2                                                                                                                                                      │
)

julia> @code_lowered f(1,2)
CodeInfo(
2 1 ─ %1 = a * b                                                                                                                                                          │
  │   %2 = %1 + b                                                                                                                                                         │
  └──      return %2                                                                                                                                                      │
)
```

```
help?> code_lowered
search: code_lowered @code_lowered

  code_lowered(f, types; generated = true)

  Return an array of the lowered forms (IR) for the methods matching the given generic function and type signature.

  If generated is false, the returned CodeInfo instances will correspond to fallback implementations. An error is thrown if no fallback implementation exists. If generated
  is true, these CodeInfo instances will correspond to the method bodies yielded by expanding the generators.

  Note that an error will be thrown if types are not leaf types when generated is true and the corresponding method is a @generated method.

help?> code_typed
search: code_typed @code_typed code_warntype @code_warntype

  code_typed(f, types; optimize=true)

  Returns an array of type-inferred lowered form (IR) for the methods matching the given generic function and type signature. The keyword argument optimize controls whether
  additional optimizations, such as inlining, are also applied.```

**Comment by crherlihy** [comment]
2. Forgot to remove `input_df`; leftover from debugging. Will fix.
3. Will use symbols in lieu of strings; |edge types| will be quite small.
4. We can de-couple extraction from data frame insertion, but we do need a way to append while iterating (that's how I've got the recursion working right now). Will experiment on making this more modular.
4b. I think generally the () and :() cases are what we encounter and need to be able to handle.
5. working on annotation stuff we talked about today. We also discussed best way to capture intermediate values while maintaining high-level vertices that will be easy to serialize in matrix format; will plan to store values in a stack associated with each vertex (which, in turn, represent functions and variables).

**Comment by jpfairbanks** [comment]
This PR is being continued on #138

**Pull request closed without merging**
