### PR TITLE
Cleaning up package dependencies

### PR DESCRIPTION
**Pull request by mehalter**
This includes a working Dockerfile, all the Travis stuff works and tests run, and all the dependencies have been cleaned up for the test and docker environments. The only test that currently doesn't run is the `odegraft.jl`.

Next PR will be documentation in the modeltools files

### CODE REVIEW

**Comment by mehalter** [comment]
Ah ignore this, travis is running into errors

**Comment by jpfairbanks** [comment]
What are we supposed to ignore?

**Comment by mehalter** [comment]
This pull request until I fix whatever is going wrong with Travis

**Comment by jpfairbanks** [comment]
Ok thanks. I fixed the ODEgraft example btw.

**Comment by mehalter** [comment]
I forgot to add the Polynomials UUID which broke Travis. Tests look good now. Ready for review and LGTM

**Pull request merged**
