### PR TITLE
NLP extraction branch

### PR DESCRIPTION
**Pull request by jpfairbanks**
@kuncao0228 I fixed your problem with running the bin/extractvars.jl script. It was because your branch was not up to date with master and was calling functions that were not defined in SemanticModels yet. Base things off of this branch going forward.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
- [ ] instructions for installing dependencies especially `en_core_web_sm` ie. `python -m spacy download en_core_web_sm`
- [ ] you use both small and medium models do we need both?
- [ ] use matplotlib styles to make the plots prettier style = ggplot would work.
- [ ] for accuracy threshold tradeoff, the number of assignments is going down exactly when the accuracy goes up. I think this is an appropriate place to present this as a Precision-recall graph. https://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html
- [ ] final cell presents an edge list, we should use graphviz to draw the resulting graph

**Comment by jpfairbanks** [comment]
I also got this error.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-ca417111cdea> in <module>()
      2 # Assigns Cluster Labels to Variable Inputs to KMeansPredicted.csv and computes accuracy by taking the difference
      3 # with the ground truth labels in JuliaDataVariable.csv
----> 4 expUtil.runKMeansExp()

~/.julia/dev/SemanticModels/examples/semanticClustering/experimentUtil.py in runKMeansExp()
    312 
    313 
--> 314     trainLabels, predictedLabels = useKmeans(trainTokenList, K_size, variableTokenList)
    315     writeCSV(kmeansTrainData, trainLabels, KMEANS_CLUSTER_LABEL_CSV_PATH)
    316     writeCSV(variable_array, predictedLabels, KMEANS_PREDICTED_CSV_PATH)

~/.julia/dev/SemanticModels/examples/semanticClustering/experimentUtil.py in useKmeans(trainTokenList, K_size, variableTokenList)
    190 
    191 def useKmeans(trainTokenList, K_size, variableTokenList):
--> 192     umapModel = umap.UMAP(random_state=42).fit(np.asarray(trainTokenList))
    193     trainEmbedding = umapModel.transform(trainTokenList)
    194     predictEmbedding = umapModel.transform(variableTokenList)

AttributeError: module 'umap' has no attribute 'UMAP'
```

**Comment by jpfairbanks** [comment]
Here is the code to visualize a graph in a notebook from Julia. We could add this as the final step in this example

```
savegraph("exampletypegraph.dot",g,DOTFormat());

run(`dot -Tsvg -O exampletypegraph.dot`);

s = read("exampletypegraph.dot.svg",String);
display("image/svg+xml",s)
```

**Comment by jpfairbanks** [comment]
Here are my package versions, what do you have 

```---------------------------------- ---------
alabaster                          0.7.10
anaconda-client                    1.6.5
anaconda-navigator                 1.6.10
anaconda-project                   0.8.2
appnope                            0.1.0
appscript                          1.0.1
argcomplete                        1.8.2
asn1crypto                         0.22.0
astroid                            1.5.3
astropy                            2.0.2
attrs                              17.3.0
Babel                              2.5.1
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.6.0
bitarray                           0.8.1
blaze                              0.11.3
bleach                             2.0.0
blis                               0.2.4
bokeh                              0.12.13
boto                               2.48.0
boto3                              1.4.8
botocore                           1.8.13
Bottleneck                         1.2.1
bz2file                            0.98
certifi                            2017.11.5
cffi                               1.11.2
chardet                            3.0.4
chest                              0.2.3
click                              6.7
cloudpickle                        0.4.0
clyent                             1.2.2
colorama                           0.3.9
conda                              4.6.7
conda-build                        3.17.8
conda-verify                       2.0.0
configobj                          5.0.6
contextlib2                        0.5.5
cryptography                       2.1.4
cycler                             0.10.0
cymem                              2.0.2
Cython                             0.27.3
cytoolz                            0.8.2
dask                               0.16.0
datashape                          0.5.4
decorator                          4.2.1
dill                               0.2.6
distributed                        1.20.2
docutils                           0.14
en-core-web-md                     2.1.0
en-core-web-sm                     2.1.0
entrypoints                        0.2.3
et-xmlfile                         1.0.1
fastcache                          1.0.2
feather-format                     0.4.0
filelock                           2.0.6
flake8                             3.5.0
Flask                              0.12.2
Flask-Cors                         3.0.3
ftfy                               4.4.3
gensim                             3.2.0
gevent                             1.2.2
glob2                              0.6
gmpy2                              2.0.8
greenlet                           0.4.12
h5py                               2.7.1
heapdict                           1.0.0
html5lib                           1.0b8
idna                               2.6
imageio                            2.2.0
imagesize                          0.7.1
imbalanced-learn                   0.3.2
imblearn                           0.0
ipykernel                          4.7.0
ipython                            6.2.1
ipython-genutils                   0.2.0
ipywidgets                         7.0.5
isort                              4.2.15
itsdangerous                       0.24
jdcal                              1.3
jedi                               0.10.2
Jinja2                             2.10
jmespath                           0.9.3
jsonschema                         2.6.0
jupyter                            1.0.0
jupyter-client                     5.1.0
jupyter-console                    5.2.0
jupyter-core                       4.4.0
jupyterlab                         0.35.4
jupyterlab-server                  0.2.0
jupytext                           1.0.2
keyring                            10.5.1
kiwisolver                         1.0.1
lazy-object-proxy                  1.3.1
libarchive-c                       2.8
lief                               0.9.0
llvmlite                           0.28.0
locket                             0.2.0
lxml                               4.1.1
MarkupSafe                         1.0
matplotlib                         3.0.3
mccabe                             0.6.1
mistune                            0.8.3
mock                               2.0.0
msgpack-numpy                      0.4.1
msgpack-python                     0.5.4
multipledispatch                   0.4.9
murmurhash                         0.28.0
nb-anacondacloud                   1.4.0
nb-conda                           2.2.1
nb-conda-kernels                   2.1.0
nbconvert                          5.3.1
nbformat                           4.4.0
nbpresent                          3.0.2
networkx                           2.1
nltk                               3.2.4
nose                               1.3.7
notebook                           5.2.2
numba                              0.43.0
numexpr                            2.6.4
numpy                              1.16.2
numpydoc                           0.7.0
odo                                0.5.1
openpyxl                           2.5.0b1
pandas                             0.24.2
pandocfilters                      1.4.1
partd                              0.3.8
path.py                            10.3.1
pathlib                            1.0.1
pathlib2                           2.3.0
patsy                              0.4.1
pbr                                3.1.1
pep8                               1.7.1
pexpect                            4.3.0
pickleshare                        0.7.4
Pillow                             3.4.2
pip                                19.0.3
pkginfo                            1.4.1
plac                               0.9.6
pluggy                             0.6.0
ply                                3.10
preshed                            2.0.1
prompt-toolkit                     1.0.15
psutil                             5.4.0
psycopg2                           2.7.3.2
ptyprocess                         0.5.2
py                                 1.5.2
pyarrow                            0.7.1
pyasn1                             0.3.7
pycodestyle                        2.3.1
pycosat                            0.6.3
pycparser                          2.18
pycrypto                           2.6.1
pycurl                             7.43.0
pyflakes                           1.6.0
Pygments                           2.2.0
pylint                             1.7.1
pymongo                            3.4.0
pyOpenSSL                          17.4.0
pyparsing                          2.2.0
PyQt5                              5.10.1
PySocks                            1.6.7
pytest                             3.3.1
python-dateutil                    2.6.1
pytz                               2017.3
PyWavelets                         0.5.2
PyYAML                             3.12
pyzmq                              16.0.2
QtAwesome                          0.4.4
qtconsole                          4.3.1
QtPy                               1.3.1
redis                              2.10.6
regex                              2017.4.5
requests                           2.18.4
requests-file                      1.4.3
rope                               0.10.7
ruamel-yaml                        0.11.14
s3transfer                         0.1.12
scikit-image                       0.13.0
scikit-learn                       0.19.1
scipy                              1.2.1
setuptools                         38.2.4
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.8
six                                1.11.0
sklearn                            0.0
smart-open                         1.5.5
snowballstemmer                    1.2.1
sockjs-tornado                     1.0.3
sortedcontainers                   1.5.7
spacy                              2.1.3
Sphinx                             1.6.5
sphinx-rtd-theme                   0.2.4
sphinxcontrib-websupport           1.0.1
spyder                             3.2.4
SQLAlchemy                         1.1.13
srsly                              0.0.5
statsmodels                        0.8.0
stevedore                          1.28.0
sympy                              1.1.1
tables                             3.4.2
tblib                              1.3.2
termcolor                          1.1.0
terminado                          0.8.1
testfixtures                       6.6.0
testpath                           0.3.1
thinc                              7.0.4
tldextract                         2.2.0
toolz                              0.8.2
tornado                            4.5.2
tqdm                               4.31.1
traitlets                          4.3.2
typing                             3.6.2
ujson                              1.35
umap                               0.1.1
umap-learn                         0.3.7
unicodecsv                         0.14.1
urllib3                            1.22
vaderSentiment                     2.5
virtualenv                         15.1.0
virtualenv-clone                   0.2.6
virtualenvwrapper                  4.8.2
ViTables                           3.0.0
wasabi                             0.2.0
wcwidth                            0.1.7
webencodings                       0.5
Werkzeug                           0.12.2
wheel                              0.30.0
widgetsnbextension                 3.0.8
wrapt                              1.10.11
xlrd                               1.1.0
XlsxWriter                         1.0.2
xlwings                            0.11.4
xlwt                               1.3.0
zict                               0.1.3
(base)```

**Comment by kuncao0228** [comment]
alabaster==0.7.12
allennlp==0.7.1
appdirs==1.4.3
appnope==0.1.0
asn1crypto==0.24.0
astroid==2.1.0
atomicwrites==1.3.0
attrs==18.2.0
aws-xray-sdk==0.95
awscli==1.15.85
Babel==2.6.0
backcall==0.1.0
bleach==3.1.0
blinker==1.4
boto==2.49.0
boto3==1.7.84
botocore==1.10.84
bz2file==0.98
cachetools==3.1.0
certifi==2019.3.9
cffi==1.11.2
chardet==3.0.4
Click==7.0
cloudpickle==0.7.0
colorama==0.3.9
conllu==0.11
cookies==2.2.1
cryptography==2.5
cycler==0.10.0
cymem==2.0.2
cytoolz==0.9.0.1
decorator==4.3.2
dicttoxml==1.7.4
dill==0.2.9
docker==3.7.0
docker-pycreds==0.3.0
docutils==0.14
ecdsa==0.13
editdistance==0.5.2
en-core-web-md==2.0.0
en-core-web-sm==2.0.0
entrypoints==0.3
flaky==3.5.3
Flask==0.12.4
Flask-Cors==3.0.3
ftfy==4.4.3
future==0.17.1
gensim==3.4.0
gevent==1.3.6
grammaregex==0.1.3
greenlet==0.4.13
h5py==2.9.0
html5lib==1.0.1
idna==2.8
ijson==2.3
imagesize==1.1.0
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
isort==4.3.4
itsdangerous==1.1.0
jedi==0.13.2
Jinja2==2.10
jmespath==0.9.3
jsondiff==1.1.1
jsonnet==0.10.0
jsonpickle==1.1
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-core==4.4.0
keyring==17.1.1
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
llvmlite==0.27.1
MarkupSafe==1.1.0
matplotlib==2.2.3
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.10
mkl-random==1.0.2
mock==2.0.0
more-itertools==4.3.0
moto==1.3.4
msgpack==0.5.6
msgpack-numpy==0.4.3.2
murmurhash==0.28.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.2
nltk==3.4
notebook==5.7.6
numba==0.42.1
numpy==1.15.4
numpydoc==0.8.0
oauthlib==2.1.0
overrides==1.9
packaging==19.0
pandas==0.24.1
pandocfilters==1.4.2
parsimonious==0.8.0
parso==0.3.2
pbr==5.1.2
pexpect==4.6.0
pickleshare==0.7.5
plac==0.9.6
pluggy==0.8.1
preshed==2.0.1
prometheus-client==0.6.0
prompt-toolkit==2.0.8
protobuf==3.6.1
psutil==5.5.0
ptyprocess==0.6.0
py==1.7.0
pyaml==18.11.0
pyasn1==0.4.4
pycodestyle==2.5.0
pycparser==2.19
pycryptodome==3.7.3
pyemd==0.5.1
pyflakes==2.1.0
Pygments==2.3.1
PyJWT==1.7.1
pylint==2.2.2
pyOpenSSL==19.0.0
pyparsing==2.3.1
Pyphen==0.9.5
PySocks==1.6.8
pytest==4.2.0
python-crfsuite==0.9.6
python-dateutil==2.8.0
python-jose==2.0.2
pytz==2017.3
PyYAML==3.13
pyzmq==17.1.2
QtAwesome==0.5.6
qtconsole==4.4.3
QtPy==1.6.0
regex==2018.1.10
requests==2.21.0
requests-oauthlib==1.0.0
responses==0.9.0
rope==0.11.0
rosette-api==1.12.1
rsa==3.4.2
s3transfer==0.1.13
scikit-learn==0.20.2
scipy==1.2.0
Send2Trash==1.5.0
singledispatch==3.4.0.3
six==1.12.0
smart-open==1.8.0
snowballstemmer==1.2.1
spacy==2.0.18
Sphinx==1.8.4
sphinxcontrib-websupport==1.1.0
spyder==3.3.3
spyder-kernels==0.4.2
sqlparse==0.2.4
tensorboardX==1.2
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
textpipeliner==0.3.1
thinc==6.12.1
toolz==0.9.0
torch==0.4.1
tornado==5.1.1
tqdm==4.31.1
traitlets==4.3.2
twython==3.7.0
typed-ast==1.1.0
typing==3.6.4
ujson==1.35
umap-learn==0.3.7
Unidecode==1.0.23
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.54.0
Werkzeug==0.14.1
wrapt==1.10.11
wurlitzer==1.0.2
xmltodict==0.12.0

**Comment by kuncao0228** [comment]
Added Metagraph creation from final subject, verb, object  csv file jupyter notebook

**Comment by jpfairbanks** [comment]
@kuncao0228 can you address the feedback here and what we discussed on Monday afternoon and get this merged by W afternoon?

**Comment by kuncao0228** [comment]
sure

**Comment by kuncao0228** [comment]
Added experiment summary to the jupyter notebook and finished updating the experiment visual graphs

**Comment by jpfairbanks** [comment]
@mehalter Does this work in our docker container?

**Comment by mehalter** [comment]
@jpfairbanks what do you think would be the best way to test this in docker? I can't run the develop command on a specific branch so I am having trouble getting this into docker to test

**Comment by jpfairbanks** [comment]
You should be able to do `Pkg.develop("SemanticModels#jpf/nlpextraction")` otherwise you can always issue a git checkout command inside the container with `docker exec $CONTAINERNAME command`

**Comment by mehalter** [comment]
This is fixed. The docker currently won't run until it is merged to master. We tested it by adding a checkout in the dockerfile, it is still there but commented out for reference. We can remove it later.

Once this gets merged and we tag a release, we need to rebuild the docker container with the tagged release github repository and push that to Dockerhub.

**Pull request merged**
